# Generated by Django 5.2.4 on 2025-07-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_raw', models.CharField(max_length=20, verbose_name='Telefonnummer (voll)')),
                ('phone_masked', models.CharField(editable=False, max_length=5)),
                ('signal_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('left', 'Ist raus'), ('needs_info', 'Braucht Infos'), ('inactive', 'Inaktiv')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kontakt',
                'verbose_name_plural': 'Kontakte',
            },
        ),
    ]
