# Generated by Django 5.2.4 on 2025-07-27 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone_masked',
        ),
    ]
