# Generated by Django 5.2.4 on 2025-08-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_token',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='activation_token_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
